### ISSUE TITLE
basic usage documentation is mission

### ISSUE THREAD

**Issue by milindpatel63** [quentinmay/discord-voice-assistant#1]
can you please explain how to use the bot...
how to get the bot to join the voice channel?
also how to trigger the bot using voiice? is there any hotword?

**Comment by quentinmay** [comment]
Once you're sure you have all necessary packages installed, join a discord voice channel, then go to a text channel and type "0follow". (Follow is the text command that makes the bot join your voice channel and listen to the users in it)
Then, the trigger word for the bot is "song" So try saying "song play nirvana". 
A couple of other voice commands are: "song stop", "song skip", "song pause", "song volume 30"
